// GENERATED CODE - DO NOT MODIFY BY HAND
// developer note - generated by running build_runner
part of 'reading_schema.dart';

// coverage:ignore-file
// ignore_for_file: duplicate_ignore, non_constant_identifier_names, constant_identifier_names, invalid_use_of_protected_member, unnecessary_cast, prefer_const_constructors, lines_longer_than_80_chars, require_trailing_commas, inference_failure_on_function_invocation, unnecessary_parenthesis, unnecessary_raw_strings, unnecessary_null_checks, join_return_with_assignment, prefer_final_locals, avoid_js_rounded_ints, avoid_positional_boolean_parameters, always_specify_types

extension GetMeterReadingCollection on Isar {
  IsarCollection<MeterReading> get meterReadings => this.collection();
}

const MeterReadingSchema = CollectionSchema(
  name: r'MeterReading',
  id: -7843023031875544205,
  properties: {
    r'readingValue': PropertySchema(
      id: 0,
      name: r'readingValue',
      type: IsarType.double,
    ),
    r'timestamp': PropertySchema(
      id: 1,
      name: r'timestamp',
      type: IsarType.dateTime,
    ),
  },
  estimateSize: _meterReadingEstimateSize,
  serialize: _meterReadingSerialize,
  deserialize: _meterReadingDeserialize,
  deserializeProp: _meterReadingDeserializeProp,
  idName: r'id',
  indexes: {},
  links: {
    r'user': LinkSchema(
      id: 5618826008492826711,
      name: r'user',
      target: r'User',
      single: true,
    ),
  },
  embeddedSchemas: {},
  getId: _meterReadingGetId,
  getLinks: _meterReadingGetLinks,
  attach: _meterReadingAttach,
  version: '3.1.0+1',
);

int _meterReadingEstimateSize(
  MeterReading object,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  var bytesCount = offsets.last;
  return bytesCount;
}

void _meterReadingSerialize(
  MeterReading object,
  IsarWriter writer,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  writer.writeDouble(offsets[0], object.readingValue);
  writer.writeDateTime(offsets[1], object.timestamp);
}

MeterReading _meterReadingDeserialize(
  Id id,
  IsarReader reader,
  List<int> offsets,
  Map<Type, List<int>> allOffsets,
) {
  final object = MeterReading();
  object.id = id;
  object.readingValue = reader.readDouble(offsets[0]);
  object.timestamp = reader.readDateTime(offsets[1]);
  return object;
}

P _meterReadingDeserializeProp<P>(
  IsarReader reader,
  int propertyId,
  int offset,
  Map<Type, List<int>> allOffsets,
) {
  switch (propertyId) {
    case 0:
      return (reader.readDouble(offset)) as P;
    case 1:
      return (reader.readDateTime(offset)) as P;
    default:
      throw IsarError('Unknown property with id $propertyId');
  }
}

Id _meterReadingGetId(MeterReading object) {
  return object.id;
}

List<IsarLinkBase<dynamic>> _meterReadingGetLinks(MeterReading object) {
  return [object.user];
}

void _meterReadingAttach(
  IsarCollection<dynamic> col,
  Id id,
  MeterReading object,
) {
  object.id = id;
  object.user.attach(col, col.isar.collection<User>(), r'user', id);
}

extension MeterReadingQueryWhereSort
    on QueryBuilder<MeterReading, MeterReading, QWhere> {
  QueryBuilder<MeterReading, MeterReading, QAfterWhere> anyId() {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(const IdWhereClause.any());
    });
  }
}

extension MeterReadingQueryWhere
    on QueryBuilder<MeterReading, MeterReading, QWhereClause> {
  QueryBuilder<MeterReading, MeterReading, QAfterWhereClause> idEqualTo(Id id) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(IdWhereClause.between(lower: id, upper: id));
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterWhereClause> idNotEqualTo(
    Id id,
  ) {
    return QueryBuilder.apply(this, (query) {
      if (query.whereSort == Sort.asc) {
        return query
            .addWhereClause(
              IdWhereClause.lessThan(upper: id, includeUpper: false),
            )
            .addWhereClause(
              IdWhereClause.greaterThan(lower: id, includeLower: false),
            );
      } else {
        return query
            .addWhereClause(
              IdWhereClause.greaterThan(lower: id, includeLower: false),
            )
            .addWhereClause(
              IdWhereClause.lessThan(upper: id, includeUpper: false),
            );
      }
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterWhereClause> idGreaterThan(
    Id id, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.greaterThan(lower: id, includeLower: include),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterWhereClause> idLessThan(
    Id id, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.lessThan(upper: id, includeUpper: include),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterWhereClause> idBetween(
    Id lowerId,
    Id upperId, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addWhereClause(
        IdWhereClause.between(
          lower: lowerId,
          includeLower: includeLower,
          upper: upperId,
          includeUpper: includeUpper,
        ),
      );
    });
  }
}

extension MeterReadingQueryFilter
    on QueryBuilder<MeterReading, MeterReading, QFilterCondition> {
  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition> idEqualTo(
    Id value,
  ) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.equalTo(property: r'id', value: value),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition> idGreaterThan(
    Id value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.greaterThan(
          include: include,
          property: r'id',
          value: value,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition> idLessThan(
    Id value, {
    bool include = false,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.lessThan(
          include: include,
          property: r'id',
          value: value,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition> idBetween(
    Id lower,
    Id upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.between(
          property: r'id',
          lower: lower,
          includeLower: includeLower,
          upper: upper,
          includeUpper: includeUpper,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  readingValueEqualTo(double value, {double epsilon = Query.epsilon}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.equalTo(
          property: r'readingValue',
          value: value,
          epsilon: epsilon,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  readingValueGreaterThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.greaterThan(
          include: include,
          property: r'readingValue',
          value: value,
          epsilon: epsilon,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  readingValueLessThan(
    double value, {
    bool include = false,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.lessThan(
          include: include,
          property: r'readingValue',
          value: value,
          epsilon: epsilon,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  readingValueBetween(
    double lower,
    double upper, {
    bool includeLower = true,
    bool includeUpper = true,
    double epsilon = Query.epsilon,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.between(
          property: r'readingValue',
          lower: lower,
          includeLower: includeLower,
          upper: upper,
          includeUpper: includeUpper,
          epsilon: epsilon,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  timestampEqualTo(DateTime value) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.equalTo(property: r'timestamp', value: value),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  timestampGreaterThan(DateTime value, {bool include = false}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.greaterThan(
          include: include,
          property: r'timestamp',
          value: value,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  timestampLessThan(DateTime value, {bool include = false}) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.lessThan(
          include: include,
          property: r'timestamp',
          value: value,
        ),
      );
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition>
  timestampBetween(
    DateTime lower,
    DateTime upper, {
    bool includeLower = true,
    bool includeUpper = true,
  }) {
    return QueryBuilder.apply(this, (query) {
      return query.addFilterCondition(
        FilterCondition.between(
          property: r'timestamp',
          lower: lower,
          includeLower: includeLower,
          upper: upper,
          includeUpper: includeUpper,
        ),
      );
    });
  }
}

extension MeterReadingQueryObject
    on QueryBuilder<MeterReading, MeterReading, QFilterCondition> {}

extension MeterReadingQueryLinks
    on QueryBuilder<MeterReading, MeterReading, QFilterCondition> {
  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition> user(
    FilterQuery<User> q,
  ) {
    return QueryBuilder.apply(this, (query) {
      return query.link(q, r'user');
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterFilterCondition> userIsNull() {
    return QueryBuilder.apply(this, (query) {
      return query.linkLength(r'user', 0, true, 0, true);
    });
  }
}

extension MeterReadingQuerySortBy
    on QueryBuilder<MeterReading, MeterReading, QSortBy> {
  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> sortByReadingValue() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'readingValue', Sort.asc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy>
  sortByReadingValueDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'readingValue', Sort.desc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> sortByTimestamp() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'timestamp', Sort.asc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> sortByTimestampDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'timestamp', Sort.desc);
    });
  }
}

extension MeterReadingQuerySortThenBy
    on QueryBuilder<MeterReading, MeterReading, QSortThenBy> {
  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> thenById() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'id', Sort.asc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> thenByIdDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'id', Sort.desc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> thenByReadingValue() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'readingValue', Sort.asc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy>
  thenByReadingValueDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'readingValue', Sort.desc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> thenByTimestamp() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'timestamp', Sort.asc);
    });
  }

  QueryBuilder<MeterReading, MeterReading, QAfterSortBy> thenByTimestampDesc() {
    return QueryBuilder.apply(this, (query) {
      return query.addSortBy(r'timestamp', Sort.desc);
    });
  }
}

extension MeterReadingQueryWhereDistinct
    on QueryBuilder<MeterReading, MeterReading, QDistinct> {
  QueryBuilder<MeterReading, MeterReading, QDistinct> distinctByReadingValue() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'readingValue');
    });
  }

  QueryBuilder<MeterReading, MeterReading, QDistinct> distinctByTimestamp() {
    return QueryBuilder.apply(this, (query) {
      return query.addDistinctBy(r'timestamp');
    });
  }
}

extension MeterReadingQueryProperty
    on QueryBuilder<MeterReading, MeterReading, QQueryProperty> {
  QueryBuilder<MeterReading, int, QQueryOperations> idProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'id');
    });
  }

  QueryBuilder<MeterReading, double, QQueryOperations> readingValueProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'readingValue');
    });
  }

  QueryBuilder<MeterReading, DateTime, QQueryOperations> timestampProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'timestamp');
    });
  }
}
